### ISSUE TITLE
Unable to resolve dependencies for message handler when migrating to .NET Core 3.0

### ISSUE THREAD

**Issue by AlexEngblom** [Particular/NServiceBus.Extensions.Hosting#21]
I'm trying to migrate to aspnetcore 3.0 and cannot figure out how to actually make the new generic host dependency approach work. I always end up with the same exception of unresolved dependencies.

If I try to use the new NServiceBus.Extensions.Hosting approach it will crash right away in when trying to build and run the software. Also using the old approaches for DI strapping it let's the software run successfully, but crashes later when trying to handle messages...

I also tried registering dependencies straight in the generic host builder, in case the issue would lie in webhostbuilder, but it didn't work either. I'm running out of ideas... If anyone has an example setup that works, I would be grateful.

Exception:

"System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed 
  (Error while validating the service descriptor 'ServiceType: MyApi.MessageHandlers.CustomerInformationUpdatedHandler 
  Lifetime: Scoped ImplementationType: MyApi.MessageHandlers.CustomerInformationUpdatedHandler': Unable to resolve service for type 'MyApi.MyDbContext' while attempting to activate 
  'MyApi.MessageHandlers.CustomerInformationUpdatedHandler'.)"

Program.cs:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
      Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder => {
          webBuilder
            .ConfigureLogging((hostingContext, logging) => {
              logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
              logging.AddDebug();
              logging.AddConsole();
              logging.AddNLog("NLog.config");
            })
            .UseNLog()
            .UseStartup<Startup>();
        })

        .UseNServiceBus(hostBuilderContext => {
          var endpoint = new EndpointConfiguration(Endpoints.PerttiApi.ToString());
          endpoint.UseSerialization<NewtonsoftSerializer>();
          var transport = endpoint.UseTransport<SqlServerTransport>();
          transport.ConnectionString("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=NServiceBus;Integrated Security=True;MultipleActiveResultSets=True");
          endpoint.GetSettings().Set(hostBuilderContext.Configuration.GetSection("NServiceBusConfiguration").Get<NServiceBusConfiguration>());
          var persistence = endpoint.UsePersistence<SqlPersistence>();
          persistence.SqlDialect<SqlDialect.MsSqlServer>();
          persistence.ConnectionBuilder(() => new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=NServiceBus;Integrated Security=True;MultipleActiveResultSets=True"));
          persistence.SubscriptionSettings().CacheFor(TimeSpan.FromMinutes(1));
          return endpoint;
     });
```

Startup.cs  -> .ConfigureServices(IServiceCollection services) I have nothing for NServiceBus and register the DbContext dependency with
 `services.AddDbContext<MyDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MyDbContext")));`

I also tried registering the dependency MyDbContext straight away in the generic host builder before NServiceBus in case this would be some issue of using webHostBuilder configuration. 
`        .ConfigureServices((hostContext, services) => {
          services.AddDbContext<MyDbContext>(options =>
            options.UseSqlServer(hostContext.Configuration.GetConnectionString("MyDbContext")));
        })`

CustomerInformationUpdatedHandler.cs
```
public class CustomerInformationUpdatedHandler : IHandleMessages<CustomerInformationUpdated> {

    private readonly MyDbContextdb db;
    private readonly ILogger<CustomerInformationUpdatedHandler> log;

    public CustomerInformationUpdatedHandler(MyDbContextdb, ILoggerFactory loggerFactory) {
      this.db = db;
      this.log = loggerFactory.CreateLogger<CustomerInformationUpdatedHandler>();
    }

    public async Task Handle(CustomerInformationUpdated message, IMessageHandlerContext context) { ... }
```

I also tried using the old approaches where I bootstrap the service container in Startup.cs instead. Also tried explicit registering of dependencies with .RegisterComponents.
This old approach actually lets the software run, and it receives the messages for handler, successfully executes the Handle logic, but afterwards it crashes somewhere in the NServiceBus internal pipeline. This results to unnecessary retries and causing multiple executions of the handler logic.

Exception when using old dependency strapping approach:

"MyApi.MessageHandlers.CustomerInformationUpdatedHandler: Information: Updated successfully
2019-11-13 17.37.45.904 INFO  Immediate Retry is going to retry message 'f2b6497c-3b53-459e-a144-ab0400fcef9b' because of an exception:
System.InvalidOperationException: Unable to resolve type: MyApi.MessageHandlers.CustomerInformationUpdatedHandler, service name: 

 ---> System.InvalidOperationException: Unresolved dependency [Target Type: MyApi.MessageHandlers.CustomerInformationUpdatedHandler], [Parameter: db(MyApi.MyDbContext)], 
 [Requested dependency: ServiceType:MyApi.MyDbContext, ServiceName:]
   at LightInject.ServiceContainer.GetEmitMethodForDependency(Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass184_0.<ResolveEmitMethod>b__2(IEmitter ms)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass184_0.<ResolveEmitMethod>b__1(IEmitter methodSkeleton)
   at LightInject.ServiceContainer.<>c__DisplayClass139_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   at LightInject.ServiceContainer.GetInstance(Type serviceType)
   at LightInject.Scope.<>c__DisplayClass22_0.<GetInstance>b__0()
   at LightInject.Scope.WithThisScope[T](Func`1 function)
   at LightInject.Scope.GetInstance(Type serviceType)
   at NServiceBus.LightInjectObjectBuilder.Build(Type typeToBuild)
   at NServiceBus.CommonObjectBuilder.Build(Type typeToBuild)
   at NServiceBus.LoadHandlersConnector.Invoke(IIncomingLogicalMessageContext context, Func`2 stage)
   at NServiceBus.ScheduledTaskHandlingBehavior.Invoke(IIncomingLogicalMessageContext context, Func`2 next)
   at NServiceBus.MutateIncomingMessageBehavior.InvokeIncomingMessageMutators(IIncomingLogicalMessageContext context, Func`2 next)
   at My.NServiceBus.Common.LoggingCorrelationScopeBehavior.Invoke(IIncomingLogicalMessageContext context, Func`1 next)
   at NServiceBus.DeserializeMessageConnector.Invoke(IIncomingPhysicalMessageContext context, Func`2 stage)
   at NServiceBus.SubscriptionReceiverBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.UnitOfWorkBehavior.InvokeUnitsOfWork(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.UnitOfWorkBehavior.InvokeUnitsOfWork(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.MutateIncomingTransportMessageBehavior.InvokeIncomingTransportMessagesMutators(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.SQLServer.ReceiveStrategy.TryProcessingMessage(Message message, TransportTransaction transportTransaction)
   at NServiceBus.Transport.SQLServer.ProcessWithNativeTransaction.TryProcess(Message message, TransportTransaction transportTransaction)
Exception details:
	Message ID: f2b6497c-3b53-459e-a144-ab0400fcef9b
	Transport message ID: 530ef0f2-0d42-48de-a2eb-5b7efd6aa385"

This doesn't seem to be specific to DbContext dependencies, but also happens with other dependencies as well...

**Comment by dvdstelt** [comment]
Maybe I'm missing something that you're doing, but I'm working on a sample myself that now uses NSB 7.2 and the new hosting package.

Here's the registration of NServiceBus inside ASP.NET Core 3.0 : https://github.com/dvdstelt/EventualConsistencyDemo/blob/litedb/EventualConsistencyDemo/Program.cs#L27
Here's the dependency injection part of LiteDb : https://github.com/dvdstelt/EventualConsistencyDemo/blob/litedb/EventualConsistencyDemo/Startup.cs#L28
Here's the handler inside ASP.NET that retrieves both SignalR Hub and LiteDb : https://github.com/dvdstelt/EventualConsistencyDemo/blob/litedb/EventualConsistencyDemo/Handlers/OrderSubmissionHandler.cs#L20

Note that it's in the `litedb` branch. On the `master` branch I'm only injecting SignalR atm.

**Comment by AlexEngblom** [comment]
Thanks for the example @dvdstelt - I was able to validate that I was actually setting everything up properly.

The real issue was that Visual Studio resolved some old nugets from projects local 'Packages' folder. Deleting the packages folder solved the issue... Classic...
